[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.12",
    "geopandas>=1.1.1",
    "matplotlib>=3.10.7",
    "rasterio>=1.4.3",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
